### ISSUE TITLE
Implicit cast generating warning

### ISSUE THREAD

**Issue by BertvanRossem** [comrob/gdip#1]
Tested with visual studio 19.

In dmath.h at line 42:

The seed is a double, while the std::default_random_engine takes a unsigned int as parameter. This is not casted and generates a warning.

Possible solution:
opendubins_random_generator = std::default_random_engine(static_cast<unsigned int>(seed));

Love your library, it's amazing!

**Comment by petvana** [comment]
I'm glad you are interested in the library. To be honest, I've never tried to compile on MSVC. I'm a little surprised if this is the only problem. I have tried to fix the type to `unsigned` for the seed. Please, check the PR if it works.

**Comment by BertvanRossem** [comment]
Works in my situation! 

There are multiple other warnings when compiling with -Wall, will create another issue for that.
