### ISSUE TITLE
NAN constant is of type float, but is assigned to double type.

### ISSUE THREAD

**Issue by BertvanRossem** [comrob/gdip#3]
When compiling on MSVC with -Wall, it generates issues since multiple classes use doubles, but in their default constructor they are assigned with NAN. (On MSVC at least), that is defined as 

`#define NAN        ((float)(INFINITY * 0.0F))`

so an implicit cast is done.

A way of getting a NAN for doubles is to use

https://en.cppreference.com/w/cpp/numeric/math/nan

`std::nan("")`

Warnings found in following files with line numbers:

angleinterval.h 32
arc.h 23
circle.h 24
point.h 39
state.h 39
stateatdistance.h 19 20
vector.h 31

**Comment by petvana** [comment]
Your message motivated me to enable continuous integration using Travis for this project. [Travis CI](https://travis-ci.com/github/comrob/gdip). Unfortunately, `-Wall` emits so many warning (like unreferenced inline function) that the compilation times out, see [stackoverflow](https://stackoverflow.com/questions/37527946/warning-unreferenced-inline-function-has-been-removed). I agree `NAN` is float, but it should not have a significant influence on performance. Any idea how to reproduce this warnings on Travis?

**Comment by BertvanRossem** [comment]
-Maybe use -W4, as is said in the SO link?
-And I assume you compile with g++, which can explain the different warnings.
-No it doesn't have any impact on the performance, it is just cleaner with it.
-I have no experience using travis, but looking at your configs, you compile with g++ and clang, so no msvc warnings will pop up. You may want to look into adding a msvc profile.

**Comment by petvana** [comment]
That is exactly what I did in CMake

https://github.com/comrob/gdip/blob/882cd126c8046cf48d1bfb2181b2d2807a9a0bbf/gdip/CMakeLists.txt#L18-L22

I have used Travis because I don't have Windows. It uses MSVC as the default compiler (not g++), see
https://travis-ci.com/github/comrob/gdip/jobs/482011786

CMake output for Windows:
```
./install.sh
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27041.0
-- The CXX compiler identification is MSVC 19.16.27041.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/travis/build/comrob/gdip/gdip/build
```

**Comment by BertvanRossem** [comment]
Ah indeed! What warnings does that produce?

**Comment by petvana** [comment]
I have fixed all warnings (except for CMake). Found no warning for `NaN` though ...

**Comment by BertvanRossem** [comment]
Nice!

Well, it isn't the biggest concern, only that I like to keep my projects warning free.

As well as 
`std::nan("")`
you can also use
`std::numeric_limits<double>::quiet_NaN()`

You can also define a new type like
`using GDIP_NAN = std::numeric_limits<double>::quiet_NaN()`
if that floats your boat.

**Comment by BertvanRossem** [comment]
Great! I will soon take a look at it.
